src/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

src/config/urls.py
from django.urls import include
from django.contrib import admin
from django.urls import path
from app import views as gr_shoping
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', gr_shoping.index, name='index'),
    path('cart/', gr_shoping.cart, name='cart'),
    path('products/<slug:category>', gr_shoping.products, name='products'),
    path('product/<int:id>', gr_shoping.product, name='product'),
    path('address/', gr_shoping.add_model_address, name='add_address_new'),
    path('thank_you/', gr_shoping.thank_you, name='thank_you'),
    path('del/', gr_shoping.del_address, name='del'),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

urlpatterns += [path('accaunts/', include('django.contrib.auth.urls'))]

src/grocery_store_project/urls.py
from django.urls import include
from django.contrib import admin
from django.urls import path
from app_grocery_shoping import views as gr_shoping
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', gr_shoping.index, name='index'),
    path('cart/', gr_shoping.cart, name='cart'),
    path('products/<slug:category>', gr_shoping.products, name='products'),
    path('product/<int:id>', gr_shoping.product, name='product'),
    path('address/', gr_shoping.add_model_address, name='add_address_new'),
    path('thank_you/', gr_shoping.thank_you, name='thank_you'),
    path('del/', gr_shoping.del_address, name='del'),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

urlpatterns += [path('accaunts/', include('django.contrib.auth.urls'))]

src/cart/models.py
from django.db import models

# Create your models here.

src/cart/forms.py
from django import forms

PRODUCT_QUANTITY_SHOICES = [(i, str(i)) for i in range(1,21)]

class CartAddProductForm(forms.Form):

    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_SHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

src/cart/views.py
import imp
from tracemalloc import get_object_traceback
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from app.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    count = 0
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
        count += 1
    context = {
        'cart': cart,
        'count':count,
    }

    return render(request, 'cart/detail.html', context)

def cart_count(request):
    cart = Cart(request)
    count = 0
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
        count += 1

    return count

src/app/templates/cart/detail.html
{% extends 'basis.html' %}
{% load static %}

{% block title %} Cart - Grocery Store {% endblock %}

{% block content %}
<div class="cart_card_wrap">
    <div class="cart_card">
        <table class="cart_table">
            <thead>
                <tr class="tr_cart">
                    <th>Image</th>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Remove</th>
                    <th>Price/kg</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart %}
                {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img class="img_cart_prod"
                                src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}"
                                alt="">
                        </a>
                    </td>
                    <td>{{ product.name|capfirst }}</td>
                    <td>
                        <form class="update" action="{% url 'cart:cart_add' product.id %}" method="post">
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.update }}
                            <input type="submit" value="Update">
                            {% csrf_token %}
                        </form>
                    </td>
                    <td>
                        <a class="remove_item" href="{% url 'cart:cart_remove' product.id %}">Remove</a>
                    </td>
                    <td class="num">${{ item.price }}</td>
                    <td class="num">${{ item.total_price }}</td>
                </tr>
                {% endwith %}
                {% endfor %}
            </tbody>
        </table>
        <div class="odrer_total">
            <p>
                Total: ${{ cart.get_total_price }}
            </p>
            <p>
                <a href="#" class="button">Make an order</a>
            </p>
        </div>
    </div>

</div>

{% endblock %}